/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JInternalFrame;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author AdMin
 */
public class MDIApplication extends javax.swing.JFrame {

    /**
     * Creates new form MDIApplication
     */
    public MDIApplication() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        this.setTitle("Gestion des Dépenses");
        this.setLocationRelativeTo(null); // Centrer la fenêtre
        javax.swing.JMenuItem rechercherPaiementItem = new javax.swing.JMenuItem("Rechercher Paiement");
        rechercherPaiementItem.addActionListener(evt -> ouvrirRecherchePaiement());
        txtrechercherPaiement.add(rechercherPaiementItem);
        
    }
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuPaiement = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        paiementMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        txtrechercherPaiement = new javax.swing.JMenu();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Gestion");

        openMenuPaiement.setMnemonic('o');
        openMenuPaiement.setText("Depense");
        openMenuPaiement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuPaiementActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuPaiement);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Etudiant");
        saveAsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveAsMenuItem);

        paiementMenuItem.setText("Paiement");
        paiementMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paiementMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(paiementMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        txtrechercherPaiement.setMnemonic('e');
        txtrechercherPaiement.setText("RecherchePaiement");
        menuBar.add(txtrechercherPaiement);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1032, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void openMenuPaiementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuPaiementActionPerformed
        // TODO add your handling code here:
         DepenseForm depenseForm = new DepenseForm();
        ouvrirForm(depenseForm);
    }//GEN-LAST:event_openMenuPaiementActionPerformed

    private void saveAsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsMenuItemActionPerformed
        // TODO add your handling code here:
         EtudiantForm etudiantForm = new EtudiantForm();
        ouvrirForm(etudiantForm);
        
    }//GEN-LAST:event_saveAsMenuItemActionPerformed

    private void paiementMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paiementMenuItemActionPerformed
         PaiementForm paiementForm = new PaiementForm();
        ouvrirForm(paiementForm); 
    }//GEN-LAST:event_paiementMenuItemActionPerformed
  private void ouvrirForm(JInternalFrame frame) {
        desktopPane.add(frame);          // ✅ Ajoute au DesktopPane
    frame.setVisible(true);          // ✅ Rendez la frame visible
    try {
        frame.setMaximum(true);      // ✅ Maximiser pour prendre tout l'espace
    } catch (Exception e) {
        e.printStackTrace();
    }
    frame.toFront();                 // ✅ Ramener devant
    frame.requestFocus();
    desktopPane.repaint();   
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
        }

        java.awt.EventQueue.invokeLater(() -> new MDIApplication().setVisible(true));
    }
     private void ouvrirRecherchePaiement() {
        RecherchePaiementForm rechercheForm = new RecherchePaiementForm();
        ouvrirForm(rechercheForm);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuPaiement;
    private javax.swing.JMenuItem paiementMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenu txtrechercherPaiement;
    // End of variables declaration//GEN-END:variables

}
